-- Import the approved Survivor 51 cast into the active season.
begin;

alter table public.season_contestants
  add column if not exists display_name text,
  add column if not exists age integer,
  add column if not exists occupation text,
  add column if not exists hometown text,
  add column if not exists current_residence text,
  add column if not exists source_url text;

create unique index if not exists season_contestants_season_name_idx
  on public.season_contestants (season_id, name);

with s as (select id from public.seasons where slug = 'survivor-51')
insert into public.season_contestants (season_id, name, display_name, tribe, age, occupation, hometown, current_residence, bio, picture_url, source_url, source_snapshot)
values
  ((select id from s), 'Aaliyah Puglia', 'Aaliyah', 'Unknown', 24, 'Chef', 'Gloucester City, New Jersey', 'Providence, Rhode Island', 'Independent chef who plans to use her experience managing personalities and building trust in competitive kitchens.', '/cast/survivor-51/aaliyah-puglia.jpg', 'https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/', '{"name":"Aaliyah Puglia","display_name":"Aaliyah","tribe":"Unknown","age":"24","occupation":"Chef","hometown":"Gloucester City, New Jersey","current_residence":"Providence, Rhode Island","bio_summary":"Independent chef who plans to use her experience managing personalities and building trust in competitive kitchens.","picture_url":"/cast/survivor-51/aaliyah-puglia.jpg","source_url":"https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/"}'::jsonb),
  ((select id from s), 'Alexis Levine', 'Alexis', 'Unknown', 34, 'Criminal defense attorney', 'Atlanta, Georgia', 'Atlanta, Georgia', 'Attorney, mother, and social strategist who plans to conceal her profession in the game.', '/cast/survivor-51/alexis-levine.jpg', 'https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/', '{"name":"Alexis Levine","display_name":"Alexis","tribe":"Unknown","age":"34","occupation":"Criminal defense attorney","hometown":"Atlanta, Georgia","current_residence":"Atlanta, Georgia","bio_summary":"Attorney, mother, and social strategist who plans to conceal her profession in the game.","picture_url":"/cast/survivor-51/alexis-levine.jpg","source_url":"https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/"}'::jsonb),
  ((select id from s), 'An Nguyen', 'Thien An', 'Unknown', 24, 'Medical student', 'Fort Worth, Texas', 'Fort Worth, Texas', 'Competitive medical student who wants to form genuine relationships while playing an aggressive strategic game.', '/cast/survivor-51/thien-an-nguyen.jpg', 'https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/', '{"name":"An Nguyen","display_name":"Thien An","tribe":"Unknown","age":"24","occupation":"Medical student","hometown":"Fort Worth, Texas","current_residence":"Fort Worth, Texas","bio_summary":"Competitive medical student who wants to form genuine relationships while playing an aggressive strategic game.","picture_url":"/cast/survivor-51/thien-an-nguyen.jpg","source_url":"https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/"}'::jsonb),
  ((select id from s), 'Ana Sani', 'Ana', 'Unknown', 34, 'Voice actress', 'Richmond Hill, Ontario, Canada', 'Toronto, Ontario, Canada', 'Longtime fan and voice actress who embraces risk and expects her cheerful personality to hide a devious side.', '/cast/survivor-51/ana-sani.jpg', 'https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/', '{"name":"Ana Sani","display_name":"Ana","tribe":"Unknown","age":"34","occupation":"Voice actress","hometown":"Richmond Hill, Ontario, Canada","current_residence":"Toronto, Ontario, Canada","bio_summary":"Longtime fan and voice actress who embraces risk and expects her cheerful personality to hide a devious side.","picture_url":"/cast/survivor-51/ana-sani.jpg","source_url":"https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/"}'::jsonb),
  ((select id from s), 'Angelica Loblack', 'Jelly', 'Unknown', 29, 'Sociology professor', 'Garland, Texas / Midwest City, Oklahoma', 'Bloomington, Indiana', 'Sociology professor who studies Survivor-style hierarchy and group dynamics with her students.', '/cast/survivor-51/jelly-loblack.jpg', 'https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/', '{"name":"Angelica Loblack","display_name":"Jelly","tribe":"Unknown","age":"29","occupation":"Sociology professor","hometown":"Garland, Texas / Midwest City, Oklahoma","current_residence":"Bloomington, Indiana","bio_summary":"Sociology professor who studies Survivor-style hierarchy and group dynamics with her students.","picture_url":"/cast/survivor-51/jelly-loblack.jpg","source_url":"https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/"}'::jsonb),
  ((select id from s), 'Brady Booker', 'Brady', 'Unknown', 27, 'Professional wrestler', 'La Salle, Illinois', 'Knoxville, Tennessee', 'Professional wrestler and outdoorsman who hopes competitors underestimate his strategic ability.', '/cast/survivor-51/brady-booker.jpg', 'https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/', '{"name":"Brady Booker","display_name":"Brady","tribe":"Unknown","age":"27","occupation":"Professional wrestler","hometown":"La Salle, Illinois","current_residence":"Knoxville, Tennessee","bio_summary":"Professional wrestler and outdoorsman who hopes competitors underestimate his strategic ability.","picture_url":"/cast/survivor-51/brady-booker.jpg","source_url":"https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/"}'::jsonb),
  ((select id from s), 'Carter Krull', 'Carter', 'Unknown', 24, 'Livestock farmer', 'Rock Rapids, Iowa', 'Sioux Falls, South Dakota', 'Farmer and entrepreneur who wants to become a trusted social player and reliable ally.', '/cast/survivor-51/carter-krull.jpg', 'https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/', '{"name":"Carter Krull","display_name":"Carter","tribe":"Unknown","age":"24","occupation":"Livestock farmer","hometown":"Rock Rapids, Iowa","current_residence":"Sioux Falls, South Dakota","bio_summary":"Farmer and entrepreneur who wants to become a trusted social player and reliable ally.","picture_url":"/cast/survivor-51/carter-krull.jpg","source_url":"https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/"}'::jsonb),
  ((select id from s), 'Cristian Chavez', 'Cristian', 'Unknown', 26, 'Head of HR', 'Salt Lake City, Utah', 'Salt Lake City, Utah', 'Energetic HR leader who plans to pair a friendly presence with a strong competitive drive.', '/cast/survivor-51/cristian-chavez.jpg', 'https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/', '{"name":"Cristian Chavez","display_name":"Cristian","tribe":"Unknown","age":"26","occupation":"Head of HR","hometown":"Salt Lake City, Utah","current_residence":"Salt Lake City, Utah","bio_summary":"Energetic HR leader who plans to pair a friendly presence with a strong competitive drive.","picture_url":"/cast/survivor-51/cristian-chavez.jpg","source_url":"https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/"}'::jsonb),
  ((select id from s), 'Danny Kilby', 'Kilby', 'Unknown', 30, 'Game designer', 'Mount Forest, Ontario, Canada', 'London, Ontario, Canada', 'Puzzle-loving game designer and dedicated fan who intends to approach Survivor creatively.', '/cast/survivor-51/danny-kilby.jpg', 'https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/', '{"name":"Danny Kilby","display_name":"Kilby","tribe":"Unknown","age":"30","occupation":"Game designer","hometown":"Mount Forest, Ontario, Canada","current_residence":"London, Ontario, Canada","bio_summary":"Puzzle-loving game designer and dedicated fan who intends to approach Survivor creatively.","picture_url":"/cast/survivor-51/danny-kilby.jpg","source_url":"https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/"}'::jsonb),
  ((select id from s), 'Devin Way', 'Devin', 'Unknown', 33, 'Actor', 'Lufkin, Texas', 'Los Angeles, California', 'Charismatic actor who plans to conceal his profession and play a loyal but strategic social game.', '/cast/survivor-51/devin-way.jpg', 'https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/', '{"name":"Devin Way","display_name":"Devin","tribe":"Unknown","age":"33","occupation":"Actor","hometown":"Lufkin, Texas","current_residence":"Los Angeles, California","bio_summary":"Charismatic actor who plans to conceal his profession and play a loyal but strategic social game.","picture_url":"/cast/survivor-51/devin-way.jpg","source_url":"https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/"}'::jsonb),
  ((select id from s), 'Eric Macksoud', 'Eric', 'Unknown', 34, 'Mental health counselor', 'Lincoln, Rhode Island', 'Windsor Locks, Connecticut', 'Counselor who hopes to build immediate rapport while remaining ready to play forcefully when challenged.', '/cast/survivor-51/eric-macksoud.jpg', 'https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/', '{"name":"Eric Macksoud","display_name":"Eric","tribe":"Unknown","age":"34","occupation":"Mental health counselor","hometown":"Lincoln, Rhode Island","current_residence":"Windsor Locks, Connecticut","bio_summary":"Counselor who hopes to build immediate rapport while remaining ready to play forcefully when challenged.","picture_url":"/cast/survivor-51/eric-macksoud.jpg","source_url":"https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/"}'::jsonb),
  ((select id from s), 'Jenna Doore', 'Jenna', 'Unknown', 30, 'Wedding photographer', 'Perrysburg, Ohio', 'Toledo, Ohio', 'Lifelong fan and photographer who believes empathy, energy, and being underestimated will help her advance.', '/cast/survivor-51/jenna-doore.jpg', 'https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/', '{"name":"Jenna Doore","display_name":"Jenna","tribe":"Unknown","age":"30","occupation":"Wedding photographer","hometown":"Perrysburg, Ohio","current_residence":"Toledo, Ohio","bio_summary":"Lifelong fan and photographer who believes empathy, energy, and being underestimated will help her advance.","picture_url":"/cast/survivor-51/jenna-doore.jpg","source_url":"https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/"}'::jsonb),
  ((select id from s), 'Kristin Flickinger', 'Kristin', 'Unknown', 49, 'Crisis management', 'Ketchum, Idaho', 'Santa Barbara, California', 'Experienced crisis manager and longtime applicant who expects to remain calm under pressure.', '/cast/survivor-51/kristin-flickinger.jpg', 'https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/', '{"name":"Kristin Flickinger","display_name":"Kristin","tribe":"Unknown","age":"49","occupation":"Crisis management","hometown":"Ketchum, Idaho","current_residence":"Santa Barbara, California","bio_summary":"Experienced crisis manager and longtime applicant who expects to remain calm under pressure.","picture_url":"/cast/survivor-51/kristin-flickinger.jpg","source_url":"https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/"}'::jsonb),
  ((select id from s), 'Lewis Kelly', 'Lewis', 'Unknown', 28, 'Farmer', 'Dublin, Ireland', 'Puerto Rico', 'Mischievous Irish farmer who lives on a small farm and brings an adventurous, adaptable outlook.', '/cast/survivor-51/lewis-kelly.jpg', 'https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/', '{"name":"Lewis Kelly","display_name":"Lewis","tribe":"Unknown","age":"28","occupation":"Farmer","hometown":"Dublin, Ireland","current_residence":"Puerto Rico","bio_summary":"Mischievous Irish farmer who lives on a small farm and brings an adventurous, adaptable outlook.","picture_url":"/cast/survivor-51/lewis-kelly.jpg","source_url":"https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/"}'::jsonb),
  ((select id from s), 'Linnea Capobianco', 'Linnea', 'Unknown', 25, 'Entrepreneur', 'Kearny, New Jersey', 'Jersey City, New Jersey', 'Confident entrepreneur who describes herself as social, logical, goofy, and willing to embrace discomfort.', '/cast/survivor-51/linnea-capobianco.jpg', 'https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/', '{"name":"Linnea Capobianco","display_name":"Linnea","tribe":"Unknown","age":"25","occupation":"Entrepreneur","hometown":"Kearny, New Jersey","current_residence":"Jersey City, New Jersey","bio_summary":"Confident entrepreneur who describes herself as social, logical, goofy, and willing to embrace discomfort.","picture_url":"/cast/survivor-51/linnea-capobianco.jpg","source_url":"https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/"}'::jsonb),
  ((select id from s), 'Maggie Nestor', 'Maggie', 'Unknown', 40, 'Farmer', 'Middleway, West Virginia', 'Charles Town, West Virginia', 'Farmer, homeschool teacher, hunter, and fisher who approaches challenges with little fear.', '/cast/survivor-51/maggie-nestor.jpg', 'https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/', '{"name":"Maggie Nestor","display_name":"Maggie","tribe":"Unknown","age":"40","occupation":"Farmer","hometown":"Middleway, West Virginia","current_residence":"Charles Town, West Virginia","bio_summary":"Farmer, homeschool teacher, hunter, and fisher who approaches challenges with little fear.","picture_url":"/cast/survivor-51/maggie-nestor.jpg","source_url":"https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/"}'::jsonb),
  ((select id from s), 'Mike Pinsky', 'Mike', 'Unknown', 32, 'Baseball executive', 'New York City', 'New York City', 'Baseball operations executive and lifelong fan who brings experience evaluating players and negotiating decisions.', '/cast/survivor-51/mike-pinsky.jpg', 'https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/', '{"name":"Mike Pinsky","display_name":"Mike","tribe":"Unknown","age":"32","occupation":"Baseball executive","hometown":"New York City","current_residence":"New York City","bio_summary":"Baseball operations executive and lifelong fan who brings experience evaluating players and negotiating decisions.","picture_url":"/cast/survivor-51/mike-pinsky.jpg","source_url":"https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/"}'::jsonb),
  ((select id from s), 'Ori Jean-Charles', 'Ori', 'Unknown', 27, 'Personal trainer', 'Spring Valley, New York', 'Spring Valley, New York', 'Personal trainer and former Division I football player focused on winning through preparation and consistency.', '/cast/survivor-51/ori-jean-charles.jpg', 'https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/', '{"name":"Ori Jean-Charles","display_name":"Ori","tribe":"Unknown","age":"27","occupation":"Personal trainer","hometown":"Spring Valley, New York","current_residence":"Spring Valley, New York","bio_summary":"Personal trainer and former Division I football player focused on winning through preparation and consistency.","picture_url":"/cast/survivor-51/ori-jean-charles.jpg","source_url":"https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/"}'::jsonb),
  ((select id from s), 'Patt Cannaday', 'Patt', 'Unknown', 33, 'Federal prosecutor', 'Tampa, Florida', 'Washington, D.C.', 'Navy prosecutor from a military family who wants to build close alliances and test herself under pressure.', '/cast/survivor-51/patt-cannaday.jpg', 'https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/', '{"name":"Patt Cannaday","display_name":"Patt","tribe":"Unknown","age":"33","occupation":"Federal prosecutor","hometown":"Tampa, Florida","current_residence":"Washington, D.C.","bio_summary":"Navy prosecutor from a military family who wants to build close alliances and test herself under pressure.","picture_url":"/cast/survivor-51/patt-cannaday.jpg","source_url":"https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/"}'::jsonb),
  ((select id from s), 'Rob Antonson', 'Rob', 'Unknown', 40, 'Airline gate agent', 'Johnston, Rhode Island', 'Cumberland, Rhode Island', 'Outgoing airline employee and father who plans to rely on conversation, competitiveness, and relationships.', '/cast/survivor-51/rob-antonson.jpg', 'https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/', '{"name":"Rob Antonson","display_name":"Rob","tribe":"Unknown","age":"40","occupation":"Airline gate agent","hometown":"Johnston, Rhode Island","current_residence":"Cumberland, Rhode Island","bio_summary":"Outgoing airline employee and father who plans to rely on conversation, competitiveness, and relationships.","picture_url":"/cast/survivor-51/rob-antonson.jpg","source_url":"https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/"}'::jsonb),
  ((select id from s), 'Sharonda Cox', 'Sharonda', 'Unknown', 34, 'OBGYN resident', 'Pompano Beach, Florida', 'Richmond, Kentucky', 'Physician who hopes to combine tenacity, practical instincts, and academic discipline in the game.', '/cast/survivor-51/sharonda-cox.jpg', 'https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/', '{"name":"Sharonda Cox","display_name":"Sharonda","tribe":"Unknown","age":"34","occupation":"OBGYN resident","hometown":"Pompano Beach, Florida","current_residence":"Richmond, Kentucky","bio_summary":"Physician who hopes to combine tenacity, practical instincts, and academic discipline in the game.","picture_url":"/cast/survivor-51/sharonda-cox.jpg","source_url":"https://www.paramountplus.com/sneak-peak/survivor-season-51-cast/"}'::jsonb)
on conflict (season_id, name) do update set
  display_name = excluded.display_name,
  tribe = excluded.tribe,
  age = excluded.age,
  occupation = excluded.occupation,
  hometown = excluded.hometown,
  current_residence = excluded.current_residence,
  bio = excluded.bio,
  picture_url = excluded.picture_url,
  source_url = excluded.source_url,
  source_snapshot = excluded.source_snapshot;

commit;
