-- Replace the initial summaries with the official Paramount+ cast bios.
-- The site owner confirmed permission to republish this text.
begin;

with official_bios(name, bio) as (
  values
    ('Aaliyah Puglia', $bio$Aaliyah is a bold, independent woman who loves watching people enjoy her cooking. As a chef, she has learned a thing or two about social politics in the kitchen. She handles egos, builds trust with her co-workers, and has learned to adapt. Aaliyah hopes to use those skills on the show and said, “I’m not here to find myself. I’m here to win the title and come back with something my family can be proud of.”$bio$),
    ('Alexis Levine', $bio$Alexis said on the YouTube livestream: “There have been people on Survivor, thus far, who have been recovering from addiction. There have been lawyers and moms. There have been really strategic women who are cunning and manipulative and savage, but you have not seen one person who is all those things, and that is me, ladies and gentlemen. Buckle up!” This wife and young mother is a social butterfly who is already planning to hide her real job in order to win.$bio$),
    ('An Nguyen', $bio$Being on Survivor is Thien An’s dream, a once-in-a-lifetime opportunity and challenge she’s ready to take on. She is set to make genuine connections and trade books for brawn as she fights to win. Thien An is competitive, wears her heart on her sleeve, and wants to “play the most authentic, cutthroat game possible.”$bio$),
    ('Ana Sani', $bio$Ana is a voice actress who has worked on several cartoons (Mysticons, Ollie’s Pack, Strawberry Shortcake: Berry in the Big City), but is ready to take the leap from animation to real life on Survivor. Ana, her sister, and mother have been watching the show since she was 9 years old. She tragically lost her mother in 2020 to cancer and will be looking to her for guidance, as she is her “north star.” “I’m going to win Survivor because I’m not afraid to take risks. I’m going to play a little deviously, and no one is going to see it coming because I’m cutesy,” said Ana.$bio$),
    ('Angelica Loblack', $bio$This curious, talkative, spontaneous, and fun young woman is a sociology professor who is a fan of the show and even uses it in her classroom. She is not outdoorsy and doesn’t like fish, but Jelly hopes to go far in the sociology experiment that is Survivor. She teaches her students that the game establishes a hierarchy and family dynamics that she hopes to use to her advantage. “I want the challenge. I want to be humbled. I want to be confronted with my biggest weaknesses so I can grow from them,” said Jelly.$bio$),
    ('Brady Booker', $bio$Brady is a professional wrestler who has appeared on AEW Dark, WWE NXT: Level Up and WWE NXT under his fighting name Bodhi Hayward. When he’s not in the ring, Brady is outdoors hunting, fishing, hiking, and camping, or he’s at home watching Survivor with his big family. “Everyone looks at me and probably thinks: ‘big, dumb jock.’ And you know what? I hope so, Brody, because that’s what I’m going to push the envelope on. The second they let their foot off the gas pedal, that’s the moment I’m going to use this brain I got in here to get after them,” Brady said.$bio$),
    ('Carter Krull', $bio$Carter likes to stay busy as he farms, drives a snow cone truck, and runs a moving company. He also dabbles in photography and videography. “Survivor has been in my DNA since I was a little kid,” said Carter. He’s been watching the game with his mother for years. Carter is a good guy who can read people pretty well and hopes to be the guy people can trust in the game.$bio$),
    ('Cristian Chavez', $bio$Cristian is a very bubbly, eccentric person with a loud laugh you won’t forget. He’s ready to give it his all on this season of Survivor. “My dad passed away a few years ago, and he ingrained in us so deeply that your own internal drive is so important, and whatever that is, go 110% into it,” said Cristian. He is a competitive person and wants to give off “little brother energy” in the game and take home the grand prize.$bio$),
    ('Danny Kilby', $bio$Kilby is a hard-working game designer and a self-professed Survivor dork who loves puzzles. He grew up in a small town with a single mom and learned how to work hard from an early age. Kilby loves the show and even met his girlfriend through an Internet Survivor game. “I’m the type of player who’s not just gonna think outside of the box. I’m gonna smash it, fasten it into a weapon, and shank my enemies with it,” said Kilby.$bio$),
    ('Devin Way', $bio$Devin Way might look familiar to some, as he is an actor who has appeared on shows like Sistas, Queer as Folk, and Grey’s Anatomy, a profession he is planning on keeping a secret while on the show. This charming, charismatic young man had a tough childhood and is not a fan of the water or the beach, but he really loves people and games. “If Joe and Devins had a baby, that is what you are looking at,” said Devin. He wants to play a strategic game without lying and backstabbing, to be a man of his word.$bio$),
    ('Eric Macksoud', $bio$Eric hopes to use his counseling skills in the game by building rapport and relationships right off the bat. He has been watching the show since he was eight and plans to do whatever it takes to bring home the grand prize. “Overall, I want to make friends with these people; however, if any of them cross me, that’s when the fangs are gonna come out. That’s when I’m gonna bite their necks, suck their blood, toss them in the ocean, and sustain,” Eric said.$bio$),
    ('Jenna Doore', $bio$Jenna is a huge fan of Survivor and even includes a clause in her wedding photography contracts warning clients that, if she achieves her “lifelong dream of going on the show,” she will not make their event. Energetic, empathetic, and determined, Jenna has been making up her own immunity challenges since she was a little girl. She connects well with people and hopes people underestimate her as a “little artist.” Jenna said this about joining the show: “I have been preparing for this, like it’s my destiny.”$bio$),
    ('Kristin Flickinger', $bio$Kristin is the oldest castaway in Season 51 at 49. She’s good in a crisis, cool, calm, and collected. Kristin has been working for the LGBTQ+ community for 25 years, the same amount of time she has been applying to be on Survivor. The show “reached into my chest and grabbed me and was like, you got to play this game,” said Kristin. She is ready for an adventure of a lifetime.$bio$),
    ('Lewis Kelly', $bio$“Everybody loves a cheeky Irish person. We have great crack, we have the best banter,” said Lewis. He is married to a Puerto Rican wife, and they live in a school bus on their tiny farm. This chaotic and mischievous farmer knows what it’s like to go on an adventure and try something completely new. He’s ready for a once-in-a-lifetime opportunity on the show and is not going to waste it.$bio$),
    ('Linnea Capobianco', $bio$Social, goofy, super logical, and not afraid to be weird, Linnea is a confident woman who runs a lingerie and adult toy business with her brother. “I’m here because I say yes to things even when I’m scared. I say yes to things that are a big challenge or that would make me super uncomfortable,” said Linnea. She has been a fan of the show since she was a kid and is excited to join the cast.$bio$),
    ('Maggie Nestor', $bio$Maggie has a degree in therapy and is a homeschool teacher to her kids. She has been watching the show since she was 15 and is ready for the challenge. Her husband thinks she’s a little crazy, but Maggie is determined and has a lot of goals for the show. She is an athletic, lifetime hunter and fisher and hopes to catch a shark and some fish while on the show and learn to make fire without flint. “I don’t really register fear. I think fear is only as large as you make it,” said Maggie.$bio$),
    ('Mike Pinsky', $bio$He is the assistant director of baseball operations, which entails advising general managers on players to trade and sign, negotiate contracts, and help teams make it to the World Series. Mike has been “playing” Survivor since he was a kid, making up challenges, pretending to be Jeff, and voting each other out. He went to Princeton, married his high school sweetheart, and is eager to enter the game and get playing. “I don’t do anything for second place. I’m here to win the game, period. Full stop,” said Mike.$bio$),
    ('Ori Jean-Charles', $bio$Book smart, street smart, and a former athlete (he played Division I football), Ori is made for Survivor. “I’m not playing for the experience, I’m not playing to make friends, I’m playing to win a million dollars and change my family’s life,” Ori said. He has done his homework of watching previous seasons and is ready to work with the women in the game. Why? Because six out of nine of the last winners were women. Ori – who describes himself as consistent – is prepared to get in game mode, lock in, and take home the grand prize.$bio$),
    ('Patt Cannaday', $bio$Patt is a Navy prosecutor who is a bit nerdy and the first woman in her family to go into the military. She comes from a military family with her husband, dad, and brother all serving. Patt is keen on challenging herself by taking on the show. As for gameplay, Patt said, “When I’m in an alliance, I want them to feel that closeness with me, but now I’m ready to go to war with any of these people.” She hopes being in the game is similar to boot camp: she was tired, exhausted, and hungry, but having a blast.$bio$),
    ('Rob Antonson', $bio$Rob is a husband and father of three kids who works for the airlines. This funny, outgoing, competitive, loving, and somewhat adventurous guy has many layers. Rob’s son told him he couldn’t do the show, so he took the challenge and applied to be on Survivor. “My secret weapon out here would be the gift of gab,” said Rob. He would love to have friends for life and make solid relationships that will survive a blindside.$bio$),
    ('Sharonda Cox', $bio$Sharonda is a doctor and wife who’s ready to take her skills and apply them to the game of Survivor. She’s spent most of her life doing things for other people, but she wants to play this game for herself and do something new. “I’ve survived my entire life, and now it’s time for me to thrive,” said Sharonda. She’s ready to use her tenacity, street smarts, and book smarts to be the Sole Survivor.$bio$)
)
update public.season_contestants as contestant
set
  bio = official_bios.bio,
  source_snapshot = jsonb_set(
    coalesce(contestant.source_snapshot, '{}'::jsonb) - 'bio_summary',
    '{bio}',
    to_jsonb(official_bios.bio)
  )
from official_bios
join public.seasons as season on season.slug = 'survivor-51'
where contestant.season_id = season.id
  and contestant.name = official_bios.name;

commit;
