-- Additive season history foundation.
-- This migration preserves the existing single-season tables and snapshots
-- their current Survivor 50 state into immutable historical records.

begin;

create table if not exists public.seasons (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  season_number integer not null unique,
  status text not null check (status in ('draft', 'active', 'finale', 'archived')),
  episode_count integer not null default 15 check (episode_count > 0),
  initial_draft_size integer not null default 5 check (initial_draft_size > 0),
  merge_draft_size integer not null default 6 check (merge_draft_size >= initial_draft_size),
  current_week integer not null default 1 check (current_week > 0),
  started_at date,
  ended_at date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists seasons_one_current_idx
  on public.seasons ((status in ('draft', 'active', 'finale')))
  where status in ('draft', 'active', 'finale');

create table if not exists public.season_contestants (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons(id) on delete restrict,
  original_contestant_id integer,
  name text not null,
  tribe text,
  prior_seasons text,
  bio text,
  picture_url text,
  is_eliminated boolean not null default false,
  elimination_day smallint,
  jury_votes_received integer not null default 0,
  source_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (season_id, original_contestant_id)
);

create table if not exists public.season_entries (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons(id) on delete restrict,
  profile_id uuid references public.profiles(id) on delete set null,
  player_name text,
  team_name text,
  avatar_url text,
  drafted_team jsonb not null default '[]'::jsonb,
  weekly_picks jsonb not null default '{}'::jsonb,
  team_points integer not null default 0,
  bonus_points integer not null default 0,
  manual_points integer not null default 0,
  final_winner_original_contestant_id bigint,
  final_wager_points integer not null default 0,
  total_score integer not null default 0,
  final_rank integer,
  created_at timestamptz not null default now(),
  archived_at timestamptz,
  unique (season_id, profile_id)
);

create table if not exists public.season_weekly_results (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons(id) on delete restrict,
  week integer not null check (week > 0),
  phase text not null check (phase in ('tribal', 'individual')),
  winner_team text,
  winner_original_contestant_id bigint,
  winner_original_contestant_ids jsonb,
  players_remaining integer,
  bonus_points_awarded integer,
  source_updated_at timestamptz,
  created_at timestamptz not null default now(),
  unique (season_id, week)
);

insert into public.seasons (
  slug, name, season_number, status, episode_count,
  initial_draft_size, merge_draft_size, current_week
)
values ('survivor-50', 'Survivor 50', 50, 'archived', 15, 5, 6, 15)
on conflict (slug) do update set
  name = excluded.name,
  season_number = excluded.season_number,
  status = 'archived',
  episode_count = excluded.episode_count,
  initial_draft_size = excluded.initial_draft_size,
  merge_draft_size = excluded.merge_draft_size,
  current_week = excluded.current_week,
  updated_at = now();

insert into public.seasons (
  slug, name, season_number, status, episode_count,
  initial_draft_size, merge_draft_size, current_week
)
values ('survivor-51', 'Survivor 51', 51, 'draft', 15, 5, 6, 1)
on conflict (slug) do update set
  name = excluded.name,
  season_number = excluded.season_number,
  status = case
    when public.seasons.status = 'archived' then public.seasons.status
    else excluded.status
  end,
  updated_at = now();

insert into public.season_contestants (
  season_id,
  original_contestant_id,
  name,
  tribe,
  prior_seasons,
  bio,
  picture_url,
  is_eliminated,
  elimination_day,
  jury_votes_received,
  source_snapshot
)
select
  s.id,
  c.id,
  c.name,
  c.tribe,
  c.season,
  c.bio,
  c.picture_url,
  coalesce(c.is_eliminated, false),
  c.elim_day,
  coalesce(c.jury_votes_received, 0),
  to_jsonb(c)
from public.contestants c
cross join public.seasons s
where s.slug = 'survivor-50'
on conflict (season_id, original_contestant_id) do update set
  name = excluded.name,
  tribe = excluded.tribe,
  prior_seasons = excluded.prior_seasons,
  bio = excluded.bio,
  picture_url = excluded.picture_url,
  is_eliminated = excluded.is_eliminated,
  elimination_day = excluded.elimination_day,
  jury_votes_received = excluded.jury_votes_received,
  source_snapshot = excluded.source_snapshot;

insert into public.season_entries (
  season_id,
  profile_id,
  player_name,
  team_name,
  avatar_url,
  drafted_team,
  weekly_picks,
  team_points,
  bonus_points,
  manual_points,
  final_winner_original_contestant_id,
  final_wager_points,
  total_score,
  final_rank,
  archived_at
)
select
  s.id,
  p.id,
  p.player_name,
  p.team_name,
  p.avatar_url,
  coalesce(p.team, '[]'::jsonb),
  coalesce(p.weekly_picks, '{}'::jsonb),
  coalesce(p.team_points, 0),
  coalesce(p.bonus_points, 0),
  coalesce(p.manual_points, 0),
  p.final_winner_pick,
  coalesce(p.final_wager_points, 0),
  coalesce(p.total_score, 0),
  rank() over (order by coalesce(p.total_score, 0) desc),
  now()
from public.profiles p
cross join public.seasons s
where s.slug = 'survivor-50'
  and p.player_name is not null
  and p.team_name is not null
on conflict (season_id, profile_id) do update set
  player_name = excluded.player_name,
  team_name = excluded.team_name,
  avatar_url = excluded.avatar_url,
  drafted_team = excluded.drafted_team,
  weekly_picks = excluded.weekly_picks,
  team_points = excluded.team_points,
  bonus_points = excluded.bonus_points,
  manual_points = excluded.manual_points,
  final_winner_original_contestant_id = excluded.final_winner_original_contestant_id,
  final_wager_points = excluded.final_wager_points,
  total_score = excluded.total_score,
  final_rank = excluded.final_rank,
  archived_at = excluded.archived_at;

insert into public.season_weekly_results (
  season_id,
  week,
  phase,
  winner_team,
  winner_original_contestant_id,
  winner_original_contestant_ids,
  players_remaining,
  bonus_points_awarded,
  source_updated_at
)
select
  s.id,
  r.week,
  r.phase,
  r.winner_team,
  r.winner_contestant_id,
  r.winner_contestant_ids,
  r.players_remaining,
  r.bonus_points_awarded,
  r.updated_at
from public.weekly_immunity_results r
cross join public.seasons s
where s.slug = 'survivor-50'
on conflict (season_id, week) do update set
  phase = excluded.phase,
  winner_team = excluded.winner_team,
  winner_original_contestant_id = excluded.winner_original_contestant_id,
  winner_original_contestant_ids = excluded.winner_original_contestant_ids,
  players_remaining = excluded.players_remaining,
  bonus_points_awarded = excluded.bonus_points_awarded,
  source_updated_at = excluded.source_updated_at;

alter table public.seasons enable row level security;
alter table public.season_contestants enable row level security;
alter table public.season_entries enable row level security;
alter table public.season_weekly_results enable row level security;

drop policy if exists "Authenticated users can read seasons" on public.seasons;
create policy "Authenticated users can read seasons"
  on public.seasons for select to authenticated using (true);

drop policy if exists "Authenticated users can read season contestants" on public.season_contestants;
create policy "Authenticated users can read season contestants"
  on public.season_contestants for select to authenticated using (true);

drop policy if exists "Authenticated users can read season entries" on public.season_entries;
create policy "Authenticated users can read season entries"
  on public.season_entries for select to authenticated using (true);

drop policy if exists "Authenticated users can read season results" on public.season_weekly_results;
create policy "Authenticated users can read season results"
  on public.season_weekly_results for select to authenticated using (true);

grant select on public.seasons to authenticated;
grant select on public.season_contestants to authenticated;
grant select on public.season_entries to authenticated;
grant select on public.season_weekly_results to authenticated;

commit;
